### PR TITLE
test: Draft test example.

### PR DESCRIPTION
**Pull request by rainwoodman**
For coverage on all of the attribute setters and the translation from info dict to the attributes.

#25

### CODE REVIEW

**Comment by rainwoodman** [comment]
@dahlb please a look if you like this approach, and we can make adjustments before I farm this out to testing real devices.

**Comment by dahlb** [comment]
it looks promising and does a nice job of mocking the api in a simple way.

I'm new to the unittest package, but I found this https://docs.python.org/3/library/unittest.html which suggests replacing
assert device.pm1 is None
with
self.assertIs(device.pm1, None)

**Comment by rainwoodman** [comment]
This is where pytest kicks in -- when we run unittests with pytest as the test driver, then pytest replaces stock assert function to include the context of the current running test as well the values of the expression nodes (just like self.assert* do). 

Another advantage of pytest as the test driver is that we are not writing the `if __name__ == '__main__':`  section which wasrequired by the stock unittest due to lack of a test driver. In addition, I recall the test fixtures (and parameterized tests) of pytest is a bit easier to use than unittest, though I don't think we will be using those any time soon.

**Comment by dahlb** [comment]
I was able to use the stock version with
```
python3 -m unittest tests/*.py
```
without adding any __main__ stuff, but pytest didn't work in my virtual env, I'll try to look at test harness choices tonight along with a github hook for running them

**Comment by rainwoodman** [comment]
I am using the home assistant core env if that helps. If we will use the
unittest driver (e.g pytest doesn’t work for you) I think we shall stick
with the unittest syntax for assertions.

**Comment by dahlb** [comment]
I figured out my env issue and got pytest working, just need to find a github hook to use

**Comment by rainwoodman** [comment]
I think we just add a new github workflow (forking lint.yaml).

**Pull request merged**
